version: "3"
services:
  kaggle-python:
    build: .
    tty: true
    entrypoint: >
      jupyter-lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=''
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ./:/workspace