name: Python Lint

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**"
      - "tests/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.13]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -U pip setuptools wheel
          pip install --no-cache-dir -r requirements.txt

      - name: Run ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true

      - name: Run mypy